/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeatingRouteImport } from './routes/seating'
import { Route as LanRouteImport } from './routes/lan'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SeatingRoute = SeatingRouteImport.update({
  id: '/seating',
  path: '/seating',
  getParentRoute: () => rootRouteImport,
} as any)
const LanRoute = LanRouteImport.update({
  id: '/lan',
  path: '/lan',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/lan': typeof LanRoute
  '/seating': typeof SeatingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/lan': typeof LanRoute
  '/seating': typeof SeatingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/lan': typeof LanRoute
  '/seating': typeof SeatingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/gallery' | '/lan' | '/seating'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/gallery' | '/lan' | '/seating'
  id: '__root__' | '/' | '/contact' | '/gallery' | '/lan' | '/seating'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LanRoute: typeof LanRoute
  SeatingRoute: typeof SeatingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seating': {
      id: '/seating'
      path: '/seating'
      fullPath: '/seating'
      preLoaderRoute: typeof SeatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lan': {
      id: '/lan'
      path: '/lan'
      fullPath: '/lan'
      preLoaderRoute: typeof LanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LanRoute: LanRoute,
  SeatingRoute: SeatingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
